In [2]:
import pandas as pd
df=pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.drop(['PassengerId',	'Name','Parch','Ticket','Cabin','Embarked'], axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp     Fare
0         0       3    male  22.0      1   7.2500
1         1       1  female  38.0      1  71.2833
2         1       3  female  26.0      0   7.9250
3         1       1  female  35.0      1  53.1000
4         0       3    male  35.0      0   8.0500

In [ ]:
target= df.Survived
inputs = df.drop('Survived',axis='columns') #droping target variable nd want to separte this
inputs

     Pclass     Sex   Age  SibSp     Fare
0         3    male  22.0      1   7.2500
1         1  female  38.0      1  71.2833
2         3  female  26.0      0   7.9250
3         1  female  35.0      1  53.1000
4         3    male  35.0      0   8.0500
..      ...     ...   ...    ...      ...
886       2    male  27.0      0  13.0000
887       1  female  19.0      0  30.0000
888       3  female   NaN      1  23.4500
889       1    male  26.0      0  30.0000
890       3    male  32.0      0   7.7500

[891 rows x 5 columns]

In [5]:
dumie= pd.get_dummies(inputs.Sex)
dumie.head(5)

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [6]:
#now we will concat these dummy variable into our dataset
inputs=pd.concat([inputs,dumie],axis='columns')
inputs.head(5)

   Pclass     Sex   Age  SibSp     Fare  female   male
0       3    male  22.0      1   7.2500   False   True
1       1  female  38.0      1  71.2833    True  False
2       3  female  26.0      0   7.9250    True  False
3       1  female  35.0      1  53.1000    True  False
4       3    male  35.0      0   8.0500   False   True

In [6]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head(10)

   Pclass   Age  SibSp     Fare  female   male
0       3  22.0      1   7.2500   False   True
1       1  38.0      1  71.2833    True  False
2       3  26.0      0   7.9250    True  False
3       1  35.0      1  53.1000    True  False
4       3  35.0      0   8.0500   False   True
5       3   NaN      0   8.4583   False   True
6       1  54.0      0  51.8625   False   True
7       3   2.0      3  21.0750   False   True
8       3  27.0      0  11.1333    True  False
9       2  14.0      1  30.0708    True  False

In [ ]:
#to check if their is any NAN value in any column
#it tells us that the age column has  nainputs.columns[inputs.isna().any()] n value

Index(['Age'], dtype='object')

In [8]:
inputs.Age[:10] #printed first 10 values in order to check the nan really exusts in our code
#we can handle thses nan values by taking the mean of the values nd then using fiilna option in order to fill those nan place

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [9]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

   Pclass        Age  SibSp     Fare  female   male
0       3  22.000000      1   7.2500   False   True
1       1  38.000000      1  71.2833    True  False
2       3  26.000000      0   7.9250    True  False
3       1  35.000000      1  53.1000    True  False
4       3  35.000000      0   8.0500   False   True
5       3  29.699118      0   8.4583   False   True
6       1  54.000000      0  51.8625   False   True
7       3   2.000000      3  21.0750   False   True
8       3  27.000000      0  11.1333    True  False
9       2  14.000000      1  30.0708    True  False

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(inputs,target,test_size=0.2)

In [11]:
len(X_train)

712

In [12]:
len(X_test)

179

gusain naive biase method
used when data distribution is normal also called bell curve

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [14]:
model.fit(X_train,Y_train)

GaussianNB()

In [15]:
model.score(X_test,Y_test)

0.7988826815642458

In [16]:
X_test[:12] # check x test sample

     Pclass        Age  SibSp     Fare  female   male
639       3  29.699118      1  16.1000   False   True
18        3  31.000000      1  18.0000    True  False
75        3  25.000000      0   7.6500   False   True
9         2  14.000000      1  30.0708    True  False
235       3  29.699118      0   7.5500    True  False
256       1  29.699118      0  79.2000    True  False
588       3  22.000000      0   8.0500   False   True
53        2  29.000000      1  26.0000    True  False
10        3   4.000000      1  16.7000    True  False
494       3  21.000000      0   8.0500   False   True
819       3  10.000000      3  27.9000   False   True
860       3  41.000000      2  14.1083   False   True

In [17]:
Y_test[:10]

639    0
18     0
75     0
9      1
235    0
256    1
588    0
53     1
10     1
494    0
Name: Survived, dtype: int64

In [18]:
model.predict(X_test[:10])

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [ ]:
model.predict_proba(X_test[:10]) #probablity method to check each class method whether person survived or not
#in this first one is the probablity of person not survived nd secod is survived we use this proba method in order to check that how much that error occured

array([[0.98509122, 0.01490878],
       [0.06625755, 0.93374245],
       [0.98295848, 0.01704152],
       [0.02091957, 0.97908043],
       [0.06100018, 0.93899982],
       [0.00104093, 0.99895907],
       [0.98216863, 0.01783137],
       [0.02896041, 0.97103959],
       [0.03660881, 0.96339119],
       [0.98183804, 0.01816196]])

In [7]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("dectree.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [13]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

df['company_n'] = le_company.fit_transform(df['company'])
df['job_n'] = le_job.fit_transform(df['job'])
df['degree_n'] = le_degree.fit_transform(df['degree'])
df=df.drop(["company","job","degree"], axis=1)

In [14]:
X = df[['company_n','job_n','degree_n']]
y = df['salary_more_then_100k']
df.head()

   salary_more_then_100k  company_n  job_n  degree_n
0                      0          2      2         0
1                      0          2      2         1
2                      1          2      0         0
3                      1          2      0         1
4                      0          2      1         0

In [48]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


x_train.shape , x_test.shape

ValueError: Found input variables with inconsistent numbers of samples: [16, 10]

In [17]:
from sklearn.naive_bayes import CategoricalNB
model= CategoricalNB()

model.fit(x_train,y_train)

CategoricalNB()

In [26]:
print(model.predict(0,1,0))
print(y_test)
print(model.score(x_test,y_test))

[1 1 0 1]
0     0
1     0
7     0
11    1
Name: salary_more_then_100k, dtype: int64
0.5

In [49]:
import pandas as pd
from sklearn.naive_bayes import BernoulliNB

In [50]:
file = pd.read_csv("new.csv")
file.head()

   Free  Offer  Win  Money  Spam
0     1      1    1      1     1
1     1      0    1      1     1
2     0      1    0      1     1
3     0      0    0      0     0
4     1      1    0      0     0

In [51]:
x = file.drop(['Spam'],axis=1)
y= file['Spam']
# y.head()

In [56]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(x,y,test_size=0.3)

In [57]:
model= BernoulliNB()
model.fit(X_train,Y_train)

BernoulliNB()

In [58]:
model.predict(X_test)

array([0, 1, 0])

In [59]:
model.score(X_test,Y_test)

1.0